import { Injectable, Logger } from '@nestjs/common';
import { IgApiClient } from 'instagram-private-api';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class InstagramAuthService {
  private readonly logger = new Logger(InstagramAuthService.name);
  private ig: IgApiClient;
  private readonly cookiesDir = path.join(process.cwd(), 'cookies');

  constructor() {
    this.ig = new IgApiClient();
    if (!fs.existsSync(this.cookiesDir)) {
      fs.mkdirSync(this.cookiesDir, { recursive: true });
    }
  }

  /**
   * .env faylidagi ma'lumotlar bilan Instagramga login qiladi 
   * va cookies papkasida yangi .txt fayl yaratadi.
   */
  async autoLoginAndGenerateCookie(): Promise<string | null> {
    const username = process.env.IG_USERNAME;
    const password = process.env.IG_PASSWORD;

    if (!username || !password || username === 'your_fake_username_here') {
      this.logger.warn("IG_USERNAME yoki IG_PASSWORD .env faylida kiritilmagan. Avto-login bekor qilindi.");
      return null;
    }

    this.logger.log(`Avtomatik login jarayoni boshlanmoqda: ${username} ...`);

    try {
      this.ig.state.generateDevice(username);
      
      // Instagram API ga login qilish
      const auth = await this.ig.account.login(username, password);
      this.logger.log(`Muvaffaqiyatli login! Akkount ID: ${auth.pk}`);

      // Kuki holatini olish
      const cookiesObj = await this.ig.state.serializeCookieJar();

      const netscapeTxt = this.convertToNetscape(cookiesObj);
      
      const fileName = `www.instagram.com_cookies_auto_${Date.now()}.txt`;
      const filePath = path.join(this.cookiesDir, fileName);
      
      fs.writeFileSync(filePath, netscapeTxt, 'utf8');
      this.logger.log(`Yangi Kuki fayli yaratildi: ${fileName}`);

      return filePath;
    } catch (error: any) {
      this.logger.error(`Avtomatik login xatosi: ${error.message}`);
      return null;
    }
  }

  /**
   * JSON formatidagi Kukilarni Netscape TXT formatiga o'tkazish
   */
  private convertToNetscape(cookieJarJson: any): string {
    let result = "# Netscape HTTP Cookie File\n";
    result += "# Generated by Instagram Auto-Login Service\n\n";

    if (!cookieJarJson.cookies) return result;

    for (const cookie of cookieJarJson.cookies) {
      const domain = cookie.domain || '.instagram.com';
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = cookie.path || '/';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expires = cookie.expires ? Math.floor(new Date(cookie.expires).getTime() / 1000) : 0;
      const name = cookie.key;
      const value = cookie.value;

      result += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}\n`;
    }

    return result;
  }
}
